v1_34_0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,7 +1,12 @@
 #!/bin/sh
-# Copyright 2005 Douglas Gregor.
+# Copyright (C) 2005, 2006 Douglas Gregor.
+# Copyright (C) 2006 The Trustees of Indiana University
+#
 # Distributed under the Boost Software License, Version 1.0.
 # (See accompanying file LICENSE_1_0.txt or http://www.boost.org/LICENSE_1_0.txt)
+
+# boostinspect:notab - Tabs are required for the Makefile.
+
 BJAM=""
 TOOLSET=""
 BJAM_CONFIG=""
@@ -27,7 +32,7 @@ do
 
     -help | --help | -h)
       want_help=yes ;;
-        
+
     -prefix=* | --prefix=*)
       PREFIX=`expr "x$option" : "x-*prefix=\(.*\)"`
       ;;
@@ -61,6 +66,10 @@ do
       ICU_ROOT=`expr "x$option" : "x-*with-icu=\(.*\)"`
       ;;
 
+    -without-icu | --without-icu )
+      flag_icu=no
+      ;;
+
     -with-libraries=* | --with-libraries=* )
       library_list=`expr "x$option" : "x-*with-libraries=\(.*\)"`
       if test "$library_list" != "all"; then
@@ -76,7 +85,7 @@ do
           done
           IFS=$old_IFS
 
-          if test "x$requested_python" != "xyes" ; then
+          if test "x$requested_python" != xyes; then
               flag_no_python=yes
           fi
       fi
@@ -90,7 +99,7 @@ do
       do
           LIBS="$LIBS --without-$library"
 
-          if test $library = "python" ; then
+          if test $library = python; then
               flag_no_python=yes
           fi
       done
@@ -145,9 +154,12 @@ Configuration:
                             library names or "all"
                             [all]
   --without-libraries=list  build all libraries except the ones listed []
-  --with-icu                enable Unicode/ICU support in Regex [disabled]
+  --with-icu                enable Unicode/ICU support in Regex 
+                            [automatically detected]
+  --without-icu             disable Unicode/ICU support in Regex
   --with-icu=DIR            specify the root of the ICU library installation
-                            and enable Unicode/ICU support in Regex [disabled] 
+                            and enable Unicode/ICU support in Regex
+                            [automatically detected]
   --with-python=PYTHON      specify the Python executable [python]
   --with-python-root=DIR    specify the root of the Python installation
                             [automatically detected]
@@ -172,27 +184,27 @@ test -n "$want_help" && exit 0
 my_dir="."
 
 # Determine the toolset, if not already decided
-if test "x$TOOLSET" = "x" ; then
-  TOOLSET=`$my_dir/tools/build/jam_src/build.sh --guess-toolset`
+if test "x$TOOLSET" = x; then
+  TOOLSET=`$my_dir/tools/jam/src/build.sh --guess-toolset`
 fi
 
 rm -f config.log
 
 # Build bjam
-if test "x$BJAM" = "x" ; then
+if test "x$BJAM" = x; then
   echo -n "Building Boost.Jam with toolset $TOOLSET... "
   pwd=`pwd`
-  cd "$my_dir/tools/build/jam_src" && ./build.sh "$TOOLSET" > config.log 2>&1
+  cd "$my_dir/tools/jam/src" && ./build.sh "$TOOLSET" > config.log 2>&1
   cd $pwd
-  arch=`cd $my_dir/tools/build/jam_src && ./bootstrap/jam0 -d0 -f build.jam --toolset=$TOOLSET --toolset-root= --show-locate-target && cd ..`
-  BJAM="$my_dir/tools/build/jam_src/$arch/bjam"
-  echo "tools/build/jam_src/$arch/bjam"
+  arch=`cd $my_dir/tools/jam/src && ./bootstrap/jam0 -d0 -f build.jam --toolset=$TOOLSET --toolset-root= --show-locate-target && cd ..`
+  BJAM="$my_dir/tools/jam/src/$arch/bjam"
+  echo "tools/jam/src/$arch/bjam"
 fi
 
 # TBD: Turn BJAM into an absolute path
 
 # If there is a list of libraries 
-if test "x$flag_show_libraries" = "xyes" ; then
+if test "x$flag_show_libraries" = xyes; then
   libraries=`$BJAM -d0 --show-libraries`
   cat <<EOF
 
@@ -210,76 +222,101 @@ EOF
 fi
 
 # Setup paths
-if test "x$EPREFIX" = "x" ; then
+if test "x$EPREFIX" = x; then
   EPREFIX=$PREFIX
 fi
 
-if test "x$LIBDIR" = "x" ; then
+if test "x$LIBDIR" = x; then
   LIBDIR="$EPREFIX/lib"
 fi
 
-if test "x$INCLUDEDIR" = "x" ; then
+if test "x$INCLUDEDIR" = x; then
   INCLUDEDIR="$PREFIX/include"
 fi
 
 # Find Python
-if test "x$flag_no_python" = "x" ; then
-    if test "x$PYTHON_VERSION" = "x" ; then
+if test "x$flag_no_python" = x; then
+  result=`$PYTHON -c "exit" > /dev/null 2>&1`
+  if [ "$?" -ne "0" ]; then
+    flag_no_python=yes
+  fi
+fi
+
+if test "x$flag_no_python" = x; then
+    if test "x$PYTHON_VERSION" = x; then
         echo -n "Detecting Python version... "
-        PYTHON_VERSION=`$PYTHON -c "import sys; print (\"%d.%d\" % (sys.version_info[0], sys.version_info[1]))" 2>&1`
-        if test $? != 0 ; then
-            echo "not found."
-            flag_no_python="yes"
-            LIBS="$LIBS --without-python"
-        else
-            echo $PYTHON_VERSION
-        fi
+        PYTHON_VERSION=`$PYTHON -c "import sys; print (\"%d.%d\" % (sys.version_info[0], sys.version_info[1]))"`
+        echo $PYTHON_VERSION
     fi
 
-    if test "x$flag_no_python" = "x" ; then
-        if test "x$PYTHON_ROOT" = "x" ; then
-            echo -n "Detecting Python root... "
-            PYTHON_ROOT=`$PYTHON -c "import sys; print sys.prefix" 2>&1`
-            if test $? != 0 ; then
-                echo "not found."
-                flag_no_python="yes"
-                LIBS="$LIBS --without-python"
-            else
-                echo $PYTHON_ROOT
-            fi
-        fi
-    fi
-
-    echo -n "Python support?... "
-    if test "x$flag_no_python" = "x" ; then
-        echo "yes."
-        BJAM_CONFIG="$BJAM_CONFIG -sPYTHON_ROOT=$PYTHON_ROOT -sPYTHON_VERSION=$PYTHON_VERSION"
-    else
-        echo "no."
-    fi
+    if test "x$PYTHON_ROOT" = x; then
+        echo -n "Detecting Python root... "
+        PYTHON_ROOT=`$PYTHON -c "import sys; print sys.prefix"`
+        echo $PYTHON_ROOT
+    fi    
 fi
 
 # Configure ICU
 echo -n "Unicode/ICU support for Boost.Regex?... "
-if test "x$flag_icu" = "xyes" ; then
-  if test "x$ICU_ROOT" = "x" ; then
-    BJAM_CONFIG="$BJAM_CONFIG -sHAVE_ICU=1"
-    echo "yes."
+if test "x$flag_icu" != xno; then
+  if test "x$ICU_ROOT" = x; then
+    COMMON_ICU_PATHS="/usr /usr/local /sw"
+    for p in $COMMON_ICU_PATHS; do
+      if test -r $p/include/unicode/utypes.h; then
+        ICU_ROOT=$p
+      fi
+    done
+  
+    if test "x$ICU_ROOT" = x; then
+      echo "not found."
+    else      
+      BJAM_CONFIG="$BJAM_CONFIG -sICU_PATH=$ICU_ROOT"
+      echo "$ICU_ROOT"
+    fi
   else
     BJAM_CONFIG="$BJAM_CONFIG -sICU_PATH=$ICU_ROOT"
     echo "$ICU_ROOT"
   fi
 else
-  echo "no."
+  echo "disabled."
 fi
 
+# Backup the user's existing user-config.jam
+JAM_CONFIG_OUT="user-config.jam"
+if test -r "user-config.jam"; then
+  counter=1
+ 
+  while test -r "user-config.jam.$counter"; do
+    counter=`expr $counter + 1`
+  done
 
+  echo "Backing up existing Boost.Build configuration in user-config.jam.$counter"
+  mv "user-config.jam" "user-config.jam.$counter"
+fi
+
+# Generate user-config.jam
+echo "Generating Boost.Build configuration in user-config.jam..."
+cat > user-config.jam <<EOF
+# Boost.Build Configuration
+# Automatically generated by Boost configure 
+
+# Compiler configuration
+using $TOOLSET ; 
+EOF
+
+#  - Python configuration
+if test "x$flag_no_python" = x; then
+  cat >> user-config.jam <<EOF
+
+# Python configuration
+using python : $PYTHON_VERSION : $PYTHON_ROOT ;
+EOF
+fi
 
 # Generate the Makefile
 echo "Generating Makefile..."
 cat > Makefile <<EOF
 BJAM=$BJAM
-TOOLSET=$TOOLSET
 BJAM_CONFIG=$BJAM_CONFIG
 PREFIX=$PREFIX
 EPREFIX=$EPREFIX
@@ -288,22 +325,22 @@ INCLUDEDIR=$INCLUDEDIR
 LIBS=$LIBS
 
 all: .dummy
-	@echo "\$(BJAM) \$(BJAM_CONFIG) -sTOOLS=\$(TOOLSET) \$(LIBS)"
-	@\$(BJAM) \$(BJAM_CONFIG) -sTOOLS=\$(TOOLSET) \$(LIBS) || \\
+	@echo "\$(BJAM) \$(BJAM_CONFIG) --user-config=user-config.jam \$(LIBS)"
+	@\$(BJAM) \$(BJAM_CONFIG) --user-config=user-config.jam \$(LIBS) || \\
 	echo "Not all Boost libraries built properly."
 
 clean: .dummy
-	rm -rf bin
+	rm -rf bin.v2
 
 distclean: clean
 	rm -rf Makefile config.log
 
 check: .dummy
-	@cd status && ../\$(BJAM) \$(BJAM_CONFIG) -sTOOLS=\$(TOOLSET) test || echo "Some Boost regression tests failed. This is normal."
+	@cd status && ../\$(BJAM) \$(BJAM_CONFIG) --user-config=../user-config.jam || echo "Some Boost regression tests failed. This is normal for many compilers."
 
 install: .dummy
-	@echo "\$(BJAM) \$(BJAM_CONFIG) --prefix=\$(PREFIX) --exec-prefix=\$(EPREFIX) --libdir=\$(LIBDIR) --includedir=\$(INCLUDEDIR) -sTOOLS=\$(TOOLSET) \$(LIBS) install"
-	@\$(BJAM) \$(BJAM_CONFIG) --prefix=\$(PREFIX) --exec-prefix=\$(EPREFIX) --libdir=\$(LIBDIR) --includedir=\$(INCLUDEDIR) -sTOOLS=\$(TOOLSET) \$(LIBS) install || echo "Not all Boost libraries built properly."
+	@echo "\$(BJAM) \$(BJAM_CONFIG) --user-config=user-config.jam --prefix=\$(PREFIX) --exec-prefix=\$(EPREFIX) --libdir=\$(LIBDIR) --includedir=\$(INCLUDEDIR) \$(LIBS) install"
+	@\$(BJAM) \$(BJAM_CONFIG) --user-config=user-config.jam --prefix=\$(PREFIX) --exec-prefix=\$(EPREFIX) --libdir=\$(LIBDIR) --includedir=\$(INCLUDEDIR) \$(LIBS) install || echo "Not all Boost libraries built properly."
 
 .dummy:
 
